steps:
  # Build the container image and push it with Kaniko
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --cache=true
      - --destination=gcr.io/$PROJECT_ID/jcon
    timeout: 1200s
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'jcon'
      - '--image'
      - 'gcr.io/$PROJECT_ID/jcon:latest'
      - '--region'
      - 'europe-north1'
      - '--allow-unauthenticated'
timeout: 1200s